/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import Dao.Member.implMember;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Brian
 */
public class LoginUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        dt();
        times();
    }
    
    public void dt()
    {
        Date d=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd EEEE");
        String dd=sdf.format(d);
        date.setText(dd);
        
    }
    SimpleDateFormat st;
    Timer t;
    public void times()
    {
        
        
        t = new Timer(0, new ActionListener() 
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            Date d=new Date();
            st=new SimpleDateFormat("HH:mm:ss");
            
            String tt=st.format(d);
            time.setText(tt);
            }
           
        
        
        
    });
        t.start();
                
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        regist = new javax.swing.JButton();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("帳號");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("密碼");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, -1));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        login.setBackground(new java.awt.Color(252, 235, 202));
        login.setFont(new java.awt.Font("標楷體", 1, 16)); // NOI18N
        login.setForeground(new java.awt.Color(153, 0, 0));
        login.setText("登入");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 174, 80, 30));

        regist.setBackground(new java.awt.Color(252, 235, 202));
        regist.setFont(new java.awt.Font("標楷體", 1, 16)); // NOI18N
        regist.setForeground(new java.awt.Color(153, 0, 0));
        regist.setText("註冊");
        regist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registMouseClicked(evt);
            }
        });
        jPanel1.add(regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 174, 80, 30));

        date.setForeground(new java.awt.Color(0, 51, 51));
        date.setText("date");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 110, -1));

        time.setForeground(new java.awt.Color(0, 51, 51));
        time.setText("time");
        jPanel1.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 50, -1));

        jLabel5.setText("先抽一支籤");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Controller/duel.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 60, -1));

        jPanel2.setBackground(new java.awt.Color(250, 230, 230));
        jPanel2.setForeground(new java.awt.Color(246, 232, 232));

        jLabel1.setFont(new java.awt.Font("標楷體", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("管理者系統");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        /*
        1.username,password-->getText()
        2.--->new implmember().query(帳號,密碼)
        3.true-->porderUI
        4.false->訊息方塊
        */
        String Username=username.getText();
        String Password=password.getText();
        if(Username.isEmpty() || Password.isEmpty())
        {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "請輸入資料");
            throw new RuntimeException();
        }
       
            
        
        
        /*if(new implMember().query(Username, Password))
        {
            dispose();//關閉本視窗
            //this.setVisible(false);//隱藏本視窗
            new PorderUI().setVisible(true);
        }
        else
        {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "無此帳號,請先註冊");
            
            dispose();//關閉本視窗
            //this.setVisible(false);//隱藏本視窗
            new add2MemberUI().setVisible(true);
        }*/
        
        //密碼錯誤?
        if(new implMember().query(Username))
        {
            if(new implMember().query1(Password))
            {
                dispose();//關閉本視窗
                //this.setVisible(false);//隱藏本視窗
                new UI().setVisible(true);
            }
            else
            {
                JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "密碼錯誤");
            
            //dispose();//關閉本視窗
            //this.setVisible(false);//隱藏本視窗
            //new add2MemberUI().setVisible(true);
            }
        }
        else
        {
            JFrame jFrame = new JFrame();
            JOptionPane.showMessageDialog(jFrame, "無此帳號請先註冊");
            
            dispose();//關閉本視窗
            //this.setVisible(false);//隱藏本視窗
            new add2MemberUI().setVisible(true);
        }
        
        
        
    }//GEN-LAST:event_loginMouseClicked

    private void registMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registMouseClicked
    // TODO add your handling code here:
        dispose();//關閉本視窗
        //this.setVisible(false);//隱藏本視窗
        new add2MemberUI().setVisible(true);
            
    }//GEN-LAST:event_registMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        JFrame jFrame = new JFrame();
        JOptionPane.showMessageDialog(jFrame,"請稍候, 容我掐指一算!");
        
        ArrayList<String> a=new ArrayList();
		a.add("請您發揮 1 號特質 : \n表現積極,善於領導");
		a.add("請您發揮 2 號特質 : \n關懷身邊朋友");
		a.add("請您發揮 3 號特質 : \n注意表達與溝通");
		a.add("請您發揮 4 號特質 : \n換一家餐廳吃,然後找家人一起");
		a.add("請您發揮 5 號特質 : \n勇於嘗試與挑戰");
		a.add("請您發揮 6 號特質 : \n多一點同理心");
		a.add("請您發揮 7 號特質 : \n少用頭腦,多享受生活");
		a.add("請您發揮 8 號特質 : \n吃下誠實豆沙包");
		a.add("請您發揮 9 號特質 : \n今天做一件善事");
		
		for (int i = 0; i <a.size();i++)  
        { 
           // generating the index using Math.random() 
            int index = (int)(Math.random() * a.size()); 
            JFrame jFrame1 = new JFrame();
            JOptionPane.showMessageDialog(jFrame1,""+ a.get(index)); 
            break;
        } 
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton login;
    private javax.swing.JTextField password;
    private javax.swing.JButton regist;
    private javax.swing.JLabel time;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
