/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Brian
 */
public class Puzzle extends javax.swing.JFrame {

    /**
     * Creates new form Puzzle
     */
    public Puzzle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        first = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        second = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        third = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fourth = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        fifth = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        sixth = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        seventh = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        eighth = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nineth = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        output3 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));

        jPanel1.setBackground(new java.awt.Color(216, 149, 83));

        first.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        first.setForeground(new java.awt.Color(255, 255, 204));
        first.setText(" 1");
        first.setToolTipText("");
        first.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        first.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                firstMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(first)
                .addGap(18, 18, 18))
        );

        jPanel2.setBackground(new java.awt.Color(242, 182, 92));

        second.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        second.setForeground(new java.awt.Color(169, 80, 36));
        second.setText(" 2");
        second.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                secondMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(second, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(second)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(216, 149, 83));

        third.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        third.setForeground(new java.awt.Color(255, 255, 204));
        third.setText(" 3");
        third.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                thirdMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(third, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(third)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(242, 182, 92));

        fourth.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        fourth.setForeground(new java.awt.Color(169, 80, 36));
        fourth.setText(" 4");
        fourth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fourthMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(fourth, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourth)
                .addGap(18, 18, 18))
        );

        jPanel9.setBackground(new java.awt.Color(249, 211, 136));

        fifth.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        fifth.setForeground(new java.awt.Color(255, 0, 0));
        fifth.setText(" 5");
        fifth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fifthMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(27, Short.MAX_VALUE)
                    .addComponent(fifth, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(fifth)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        jPanel8.setBackground(new java.awt.Color(242, 182, 92));

        sixth.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        sixth.setForeground(new java.awt.Color(169, 80, 36));
        sixth.setText(" 6");
        sixth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sixthMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(sixth, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(sixth)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(216, 149, 83));

        seventh.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        seventh.setForeground(new java.awt.Color(255, 255, 204));
        seventh.setText(" 7");
        seventh.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                seventhMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(seventh, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seventh)
                .addGap(15, 15, 15))
        );

        jPanel6.setBackground(new java.awt.Color(242, 182, 92));

        eighth.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        eighth.setForeground(new java.awt.Color(169, 80, 36));
        eighth.setText(" 8");
        eighth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                eighthMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(eighth, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(eighth)
                .addGap(18, 18, 18))
        );

        jPanel7.setBackground(new java.awt.Color(216, 149, 83));

        nineth.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 48)); // NOI18N
        nineth.setForeground(new java.awt.Color(255, 255, 204));
        nineth.setText(" 9");
        nineth.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ninethMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(nineth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nineth)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 248, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        one.setBackground(new java.awt.Color(253, 211, 211));
        one.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        one.setForeground(new java.awt.Color(51, 0, 153));
        one.setText("命數1");
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oneMouseClicked(evt);
            }
        });
        jPanel12.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 40));

        two.setBackground(new java.awt.Color(253, 211, 211));
        two.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        two.setForeground(new java.awt.Color(51, 0, 153));
        two.setText("命數2");
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoMouseClicked(evt);
            }
        });
        jPanel12.add(two, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 40));

        three.setBackground(new java.awt.Color(253, 211, 211));
        three.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        three.setForeground(new java.awt.Color(51, 0, 153));
        three.setText("命數3");
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                threeMouseClicked(evt);
            }
        });
        jPanel12.add(three, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 40));

        jPanel13.setBackground(new java.awt.Color(240, 240, 255));

        jLabel2.setFont(new java.awt.Font("標楷體", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 102));
        jLabel2.setText("感情配對");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(116, 116, 116))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 324, 60));

        four.setBackground(new java.awt.Color(253, 211, 211));
        four.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        four.setForeground(new java.awt.Color(51, 0, 153));
        four.setText("命數4");
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fourMouseClicked(evt);
            }
        });
        jPanel12.add(four, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 40));

        five.setBackground(new java.awt.Color(253, 211, 211));
        five.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        five.setForeground(new java.awt.Color(51, 0, 153));
        five.setText("命數5");
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fiveMouseClicked(evt);
            }
        });
        jPanel12.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 40));

        six.setBackground(new java.awt.Color(253, 211, 211));
        six.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        six.setForeground(new java.awt.Color(51, 0, 153));
        six.setText("命數6");
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sixMouseClicked(evt);
            }
        });
        jPanel12.add(six, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, 40));

        seven.setBackground(new java.awt.Color(253, 211, 211));
        seven.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        seven.setForeground(new java.awt.Color(51, 0, 153));
        seven.setText("命數7");
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sevenMouseClicked(evt);
            }
        });
        jPanel12.add(seven, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        eight.setBackground(new java.awt.Color(253, 211, 211));
        eight.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        eight.setForeground(new java.awt.Color(51, 0, 153));
        eight.setText("命數8");
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eightMouseClicked(evt);
            }
        });
        jPanel12.add(eight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, 40));

        nine.setBackground(new java.awt.Color(253, 211, 211));
        nine.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        nine.setForeground(new java.awt.Color(51, 0, 153));
        nine.setText("命數9");
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nineMouseClicked(evt);
            }
        });
        jPanel12.add(nine, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 40));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(250, 237, 237));

        jLabel1.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("整體分析");

        output2.setBackground(new java.awt.Color(252, 246, 246));
        output2.setColumns(20);
        output2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        output2.setForeground(new java.awt.Color(0, 153, 153));
        output2.setRows(5);
        jScrollPane1.setViewportView(output2);

        jButton1.setBackground(new java.awt.Color(218, 218, 252));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("列印 (上)");
        jButton1.setActionCommand("列印I");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(249, 233, 233));
        jButton2.setFont(new java.awt.Font("標楷體", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("離開");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        output3.setBackground(new java.awt.Color(252, 246, 246));
        output3.setColumns(20);
        output3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 16)); // NOI18N
        output3.setForeground(new java.awt.Color(204, 51, 0));
        output3.setRows(5);
        jScrollPane2.setViewportView(output3);

        jLabel3.setFont(new java.awt.Font("標楷體", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 0));
        jLabel3.setText("配對分析");

        jButton3.setBackground(new java.awt.Color(218, 218, 252));
        jButton3.setText("列印 (下)");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel3))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstMouseMoved
        output2.setText("生命靈數1號，也叫做創始數\n" 
                + "\n1號人在執行任務的過程中，\n"
                + "通常喜歡並需要規劃或是建立\n"
                + "一套屬於自己的方式、自己的領域、自己的圈子。\n"
                + "1號人在乎的不是大小、人數，\n"
                + "1號人在乎的是如何在團體中樹立起個人標準，\n"
                + "讓身邊的人感到佩服並願意跟隨。");
    }//GEN-LAST:event_firstMouseMoved

    private void secondMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondMouseMoved
        output2.setText("生命靈數2號，也叫做平衡數\n"
                + "\n2號人很享受調解雙邊矛盾和衝突的過程，\n"
                + "他們擁有以柔克剛的能力，\n"
                + "擅長以一個平衡者的角色\n"
                + "來幫助團體達到集體成功的目標，\n"
                + "並將資源做到公平的最佳分配，\n"
                + "希望讓大家都能對結果感到滿意\n"
                + "並感謝2號人的協調與努力。");

                
   
    }//GEN-LAST:event_secondMouseMoved

    private void thirdMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thirdMouseMoved
        output2.setText("生命靈數3號，也叫做表達數\n"
                + "\n3號人具有旺盛的好奇心，樂觀且善於溝通，\n"
                + "具有孩子般的童心和多變性。\n"
                + "3號人有著天馬行空的想像力，\n"
                + "以及突破現況的超強能力，\n"
                + "能持續輸出超級與眾不同的好點子和創新的契機點\n"
                + "讓3號人感覺到幸福和存在的價值。");
    }//GEN-LAST:event_thirdMouseMoved
        
    
            
    private void fifthMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fifthMouseMoved
       output2.setText("生命靈數5號，也叫做自由數\n"
               + "\n5號人擁有自由的靈魂，\n"
               + "致力於追求身心自由、不受約束，\n"
               + "希望能隨心所欲掌管自己的人生和\n"
               + "隨時擁有自己想要的空間。\n"
               + "當5號人面對壓力和第一次嘗試的事物時，\n"
               + "較能帶著冒險精神及\n"
               + "隨遇而安的特質來解決任務，\n"
               + "因為5 號人深信，\n"
               + "只要自己願意就沒有做不到的事情。");
                       
    }//GEN-LAST:event_fifthMouseMoved

    private void sixthMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixthMouseMoved
        output2.setText("生命靈數6號，也叫做奉獻數\n" 
                + "\n6號人重視親情，對親情、友情\n"
                + "以及愛情的需求非常強烈和渴望，\n"
                + "這讓6號人願意主動\n"
                + "先讓對方感受到自己的誠意和愛意，\n"
                + "希望經由這般主動且溫暖的相處過程，\n"
                + "讓自己順利走進婚姻生活。\n"
                + "家庭美滿和持續接收到滿滿的愛，\n"
                + "就是6號人重要的人生目標之一。");
    }//GEN-LAST:event_sixthMouseMoved

    private void seventhMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seventhMouseMoved
        output2.setText("生命靈數7號，也叫做幸運數\n" 
                + "\n7號人被視為與神有著神祕連結的象徵，\n"
                + "如同西方人常說的「Lucky 7」，\n"
                + "7號人的內心會一直找尋\n"
                + "與他人在精神方面的深度連結，\n"
                + "以及探詢事情的深度意義。7號人的直覺性非常高，\n"
                + "也因為這樣天生的絕對感受能力，\n"
                + "讓7號人本質中住著一個嚴格的靈魂，\n"
                + "對萬物的標準非常高，\n"
                + "往往需要看到事實證據才會選擇相信。");
    }//GEN-LAST:event_seventhMouseMoved

    private void eighthMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eighthMouseMoved
        output2.setText("生命靈數8號，也叫做因果數\n"
                + "\n8號人在乎的是在生活或職場中，\n"
                + "是否擁有統治、控制的權力，\n"
                + "同時也非常看重個人成就的展現與財富的累積。\n"
                + "因果數的特質，讓8號人的本質上非常重視效率、\n"
                + "執行力，並願意身體力行。\n"
                + "8號人不愛空想，那會讓他們覺得不夠實際，\n"
                + "他們更看重的是掌握在自己手中的東西，\n"
                + "盡量不做自己沒有把握的事情。");
    }//GEN-LAST:event_eighthMouseMoved

    private void ninethMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ninethMouseMoved
        output2.setText("生命靈數9號，也叫做大愛數\n"
                + "\n9號人希望世界和平，\n"
                + "並期待全人類都可以過著幸福美滿的生活。\n"
                + "他們追求心靈層面的提升，\n"
                + "因為9 號人對於精神層面有著很高的期待和要求，\n"
                + "希望自己給人的正面感受是熱心公益、心懷慈悲，\n"
                + "願意在能力範圍之內照顧所有需要幫助的人。");
        
    }//GEN-LAST:event_ninethMouseMoved

    private void fourthMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourthMouseMoved
        output2.setText("生命靈數4號，也叫做執行數\n" 
                +"\n4號人的強項就是實現和做出來，\n"
                + "實際執行的同時也非常謹慎、\n" 
                + "講求規矩，並努力遠離風險。\n"
                + "面對風險較高的事物時，\n"
                + "會花時間評估成功的機率以及需要付出的代價，\n"
                + "因為4 號人希望\n"
                + "自己的每一步都往正確的方向前進，\n"
                + "才能幫自己累積更多的資源和財富。");
        
    }//GEN-LAST:event_fourthMouseMoved

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            output2.print();
        }
        catch (PrinterException ex) {
            Logger.getLogger(Puzzle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oneMouseClicked
        output3.setText("生命靈數 1號人\n"
                + "\n天生自帶領頭羊的特質，\n"
                + "這樣的人格特質反映在感情上，\n"
                + "你們渴望擔任「主導者」的角色。\n"
                + "正因為1號人所散發出的領導才能，\n"
                + "在相處上也很容易成為照顧者的角色，\n"
                + "如果你們可以遇到一個\n"
                + "珍惜並欣賞你為愛付出的霸氣個性，\n"
                + "1號人也會回饋給對方暖暖的愛意與寵愛。\n");
        
    }//GEN-LAST:event_oneMouseClicked

    private void twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoMouseClicked
        output3.setText("生命靈數 2號人\n"
                + "\n有著合群、協調的特質\n"
                + "與成就他人的胸襟與氣度，\n"
                + "你們通常很願意為了在意的人付出，\n"
                + "當你們遇到你們在意的對象時，\n"
                + "你們也願意配合對方，\n"
                + "擔任這段感情中的協調者。\n"
                + "若是2號人在一段關係中，\n"
                + "可以遇到一位能理解你\n"
                + "之所以願意在相處和溝通時退讓，\n"
                + "並不是因為沒有主見，而是你們柔軟的心，\n"
                + "不願看到任何一方有所傷害。\n"
                + "當對方能夠理解你的這一點，\n"
                + "你的付出就能夠感受到相等的回應和安全感。"
                );
        
    }//GEN-LAST:event_twoMouseClicked

    private void threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_threeMouseClicked
        output3.setText("生命靈數 3號人\n"
                + "\n充滿想像力和幽默感，\n"
                + "在生活中總是扮演開心果的角色，\n"
                + "你們受不了一成不便枯燥乏味的日子，\n"
                + "因此對於3號人來說，保有彈性和不設限未來很重要，\n"
                + "你們認為最好的愛情\n"
                + "是一起經歷許多起起伏伏才能達到彼此的平衡點。\n"
                + "但有時候3號人的個性也相當令人捉摸不定，\n"
                + "時而甜蜜時而讓你抓狂。\n"
                + "因此若你在一段關係中，\n"
                + "能遇到欣賞你面對愛情難題時，\n"
                + "勇於嘗試和不放棄的特質，\n"
                + "就能在這段關係中持續創造新鮮感。\n"
        );
        
    }//GEN-LAST:event_threeMouseClicked

    private void fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fourMouseClicked
        output3.setText("生命靈數 4號人\n"
                + "\n是個安全感極強的數字，\n"
                + "你們對自己要求極高，\n"
                + "事事都相當認真和努力，\n"
                + "期待自己藉由努力讓生活和\n"
                + "感情一點一點走向你心目中的穩定狀態，\n"
                + "一段感情一定要讓你們覺得很踏實、\n"
                + "關係穏定正常，你們不能忍受變動不穏定、猜忌的情況。\n"
                + "若4號人遇到欣賞你追求細節與SOP的對象，\n"
                + "你便能夠在這段感情中擔任最佳防守員的角色，\n"
                + "也能用你追求零風險的態度守護著你們的愛情，\n"
                + "讓你的對象感受到濃濃的安全感。");
        
    }//GEN-LAST:event_fourMouseClicked

    private void fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fiveMouseClicked
        output3.setText("生命靈數 5號人\n"
                + "\n是一個天生散發光芒的發光體，\n"
                + "你在人群中總是能成為群眾的焦點，\n"
                + "甚至常常能擔任引領潮流的角色，\n"
                + "對5號人來說，愛情只是生活裡的一部分而非全部，\n"
                + "你們覺得世界上還有很多好玩的事要嚐試，\n"
                + "因此另外一半給予空間和自由也特別重要。\n"
                + "跟5號人談戀愛，\n"
                + "別忘記與他分享你內心中渴望的自由，\n"
                + "這樣他才能跟隨著你的腳步\n"
                + "與你一起通往屬於你們的愛情道路。\n");
        
    }//GEN-LAST:event_fiveMouseClicked

    private void sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sixMouseClicked
        output3.setText("生命靈數 6號人\n"
                + "\n是標準甜膩型的戀人，\n"
                + "你們渴望穩定且互相理解的愛情，\n"
                + "也期待能與另一半的家庭、\n"
                + "朋友保持良好的關係，\n"
                + "愛屋及烏的特質\n"
                + "讓你的對象很願意將他的未來交託在你手中。\n"
                + "若你在一段關係中，\n"
                + "能遇到用對等且願意主動回應愛情的對象，\n"
                + "你便可以安心且主動地付出，\n"
                + "在這樣珍惜的過程，\n"
                + "你相對也可以享受對等甚至加倍回應的愛。\n");
        
    }//GEN-LAST:event_sixMouseClicked

    private void sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sevenMouseClicked
        output3.setText("生命靈數 7號人\n"
                + "\n擁有多樣化的興趣，對世界總是充滿好奇，\n"
                + "並期許自己可以經由學習新事物的過程，\n"
                + "讓自己成為關係相處中萬能的角色，\n"
                + "你們看待事物不會只看表面的價值，\n"
                + "且相當擅於分析，\n"
                + "你也很希望自己可以成為另一半交流和討論的對象，\n"
                + "因為對你來說，\n"
                + "一起探索和進步的過程是專屬於你們的甜蜜時刻。\n"
                + "因此若可以在一段關係中，\n"
                + "遇到願意耐心聆聽或討論的對象，\n"
                + "你便可以在這段愛情中教學相長，\n"
                + "享受一起進步所帶來的快樂。\n"
                );
        
    }//GEN-LAST:event_sevenMouseClicked

    private void eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eightMouseClicked
        output3.setText("生命靈數 8號人\n"
                + "\n自帶獨力的性格，在團體裡面為了維持和諧，\n"
                + "常常會掩飾自己真正的感受，\n"
                + "但其實在你們冷漠的外表下，\n"
                + "藏著澎派的情感，一旦你們認定對方是自己人，\n"
                + "變會無條件的奉獻自己，\n"
                + "你們很希望可以與你在意的人一起完成共同目標。\n"
                + "8號人在性格上比較早熟，\n"
                + "你們很擅長照顧好自己跟別人，\n"
                + "但其實真正了解你的人少之又少，\n"
                + "若你可以在一段關係中，\n"
                + "遇到主動與你分享和邀請你參與多元事務的伴侶，\n"
                + "你便可以在愛情中成為成就他人的角色，\n"
                + "同時也感受到被愛的感覺。");
       
    }//GEN-LAST:event_eightMouseClicked

    private void nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nineMouseClicked
        output3.setText("生命靈數 9號人\n"
                + "\n生活態度是為了夢想、信念而堅持和努力，\n"
                + "因此9號人可說是一個天生的信徒，\n"
                + "你們認為心中一定要有某種的信念和信仰，\n"
                + "才會有個明確想要努力和進步的目標。\n"
                + "你一直以來都是一位負責任的人，\n"
                + "而這個特質同時也反映在你的生活中，\n"
                + "你在相處過程中會為了\n"
                + "自己相信的人事物不斷嘗試和不輕易放棄，\n"
                + "因此想要吸引9號人，\n"
                + "不管在物質或是精神靈性才華各方面，\n"
                + "都要能夠匹配，你才能認定對方。");
        
    }//GEN-LAST:event_nineMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        try {
            output3.print();
        }
        catch (PrinterException ex) {
            Logger.getLogger(Puzzle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eight;
    private javax.swing.JLabel eighth;
    private javax.swing.JLabel fifth;
    private javax.swing.JLabel first;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel fourth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nine;
    private javax.swing.JLabel nineth;
    private javax.swing.JButton one;
    private javax.swing.JTextArea output2;
    private javax.swing.JTextArea output3;
    private javax.swing.JLabel second;
    private javax.swing.JButton seven;
    private javax.swing.JLabel seventh;
    private javax.swing.JButton six;
    private javax.swing.JLabel sixth;
    private javax.swing.JLabel third;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    // End of variables declaration//GEN-END:variables
}
